### PR TITLE
Change binding address to support running bref server inside a docker container

### PR DESCRIPTION
**Pull request by hungvietdo**
This change will allow access from host to a docker container which is running bref server.

### CODE REVIEW

**Comment by mnapoli** [comment]
Thanks!

**Comment by zagovorichev** [comment]
@mnapoli hm... it won't work if you don't fix [bin](https://github.com/brefphp/dev-server/tree/0.2.2/bin)/bref-dev-server

**Comment by mnapoli** [comment]
@zagovorichev could you clarify?

**Comment by zagovorichev** [comment]
@mnapoli sure: You still have 127.0.0.1:8000 hardcoded here:
https://github.com/brefphp/dev-server/blob/0.2.2/bin/bref-dev-server#L25

And when you run `vendor/bin/bref-dev-server` it will use localhost, but for docker we need to use 0.0.0.0:8000, correct?

**Comment by mnapoli** [comment]
Good point, the class updated here was actually not used. I've cleaned that up and tagged a new release. Thanks!

**Pull request merged**
